### ISSUE TITLE
buggy android add-on native-ui-boilerplate

### ISSUE THREAD

**Issue by gitagon** [mozilla/firefox-for-android-addons#5]
I implemented an add-on for fennec, and as recommended, using the native-ui-boilerplate from
https://github.com/mozilla/firefox-for-android-addons

I realized with this code, the add-on menu entry disappeared after restarting Firefox for Android.

I grew some grey hairs assuming the problem must be in my own code, because the template must be correct... 
In a nutshell, I discovered in bootstrap.js, the domWindow variable initialization has been removed last year from the onOpenWindow handler in line 66, therefore causing all calls to domWindow methods fail:
https://github.com/mozilla/firefox-for-android-addons/commit/45c85215a89c9a965cf99378b9bca30c6d3ce1b3

Now I wonder if this line has been removed because of some API deprecation or "dirty" internals and what a "clean" fix should be like, maybe just something like this?
let domWindow = aWindow.QueryInterface(Ci.nsIInterfaceRequestor).getInterface(Ci.nsIDOMWindow);

NOTE: also filed this on bugzilla hoping it will prevent someone else from running into the same time-consuming trap.

**Comment by leibovic** [comment]
Thank you for reporting, and I'm sorry about that! Would you be interested in creating a pull request for the template? If not, I will try to find time to get to this soon.

**Comment by gitagon** [comment]
Fixed with pull req commit
https://github.com/mozilla/firefox-for-android-addons/pull/6
