### ISSUE TITLE
JNI Examples

### ISSUE THREAD

**Issue by Noitidart** [mozilla/firefox-for-android-addons#7]
This JNI example is so cool!

https://github.com/mozilla/firefox-for-android-addons/blob/355f9a01464a0794c1084e8fdbab92c58503f49a/snippets/jni.js

I was trying to take a screenshot as per this stackoverflow topic:

> http://stackoverflow.com/a/31346510/5062337
> If you want to take a screenshot from your own program you can get the main View and make it draw itself into a Bitmap and save it (this way the system bars will not be present on the image).

Would you be able to help me out, Im learning JNI. As  soon as I do I'll update MDN, that's what I did with WinAPI, COM, GTK, GDK, etc: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Standard_OS_Libraries

I help out lots of people on Stackoverflow and irc so you helping me would not be just a one to one. It will be one to many :)

**Comment by leibovic** [comment]
I'm not very familiar with JNI myself, most of what I learned was through working on this example. You should try asking in #mobile on irc.mozilla.org, since there are multiple people who hang out there who have more experience with JNI. Sorry I can't be more helpful!

**Comment by Noitidart** [comment]
Thanks very much for that I  actually just got help from them and I hope now that I can be helpful to you! :)

Check out this gist its my first example: https://gist.github.com/Noitidart/400261f83b1be721a93a#comment-1492825

It follows the demo on the android docs page: http://developer.android.com/guide/topics/ui/notifiers/toasts.html#q=Toast

It teaches you how to read the docs and translate it to JNI but you have to read the long chat and the number one missing link was the types page on JNI docs :)
