### ISSUE TITLE
Adding button for some selected texts in Firefox Android browser

### ISSUE THREAD

**Issue by dipeshkalyani** [mozilla/firefox-for-android-addons#9]
Hi,

Need a help. I wanted to know if its possible to implement a firefox add-on which shows a button whenever it sees a particular text in the loaded webpage. For eg: say, showing a call button whenever it sees any number.
I tried searching across the APIs but could get any straightforward approach. 
Please let me know if there are any such existing sample code or add-ons I can refer to or the API I can investigate to start with the implementation.

**Comment by mcomella** [comment]
Hi @dipeshkalyani.

Unfortunately, this repository is for sample Firefox add-ons and isn't a help forum so I can't guarantee further help here. For future help, you could post to the [addons Discourse](https://discourse.mozilla-community.org/c/add-ons) or see the "Contact us" header on [the Add-ons page on MDN](https://developer.mozilla.org/en-US/Add-ons) for other options (IRC, mailing lists).

If you're writing a new add-on, I'd recommend using [the WebExtension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) - other add-on APIs are deprecated & will soon be removed. On Android, to show a button, you could use [the PageAction API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) or, *I think* [the BrowserAction API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction) but at this point BrowserAction is not yet fully implemented and has minimal support in our Nightly Firefox builds only.

If you still need help, you should be able to get more extensive help from Discourse or one of the other sources above.
